# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0002_student_activated'),
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_created', models.DateTimeField(auto_now_add=True)),
                ('response_team_activated', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboard.District')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboard.Student')),
            ],
        ),
    ]
